const segments = [
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Issuance",
    event_date: "2023-09-13T03:13:50",
    document_type: "TICKET",
    Event_number: "0",
    Event_version: "0",
    Event_entity_status: "NOT CONFIRMED",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2024-01-25T09:10:21",
    document_type: "TICKET",
    Event_number: "8",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2024-01-25T09:10:20",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2024-01-24T22:49:41",
    document_type: "TICKET",
    Event_number: "6",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2023-12-22T23:06:35",
    document_type: "TICKET",
    Event_number: "3",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Association",
    event_date: "2023-12-22T08:11:49",
    document_type: "TICKET",
    Event_number: "1",
    Event_version: "1",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2023-12-22T23:04:11",
    document_type: "TICKET",
    Event_number: "2",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2024-01-24T22:51:53",
    document_type: "TICKET",
    Event_number: "7",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2023-12-23T09:00:46",
    document_type: "TICKET",
    Event_number: "5",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2024-01-25T09:12:36",
    document_type: "TICKET",
    Event_number: "9",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2024-01-25T09:10:20",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Confirm Issuance",
    event_date: "2023-09-14T00:39:46",
    document_type: "TICKET",
    Event_number: "0",
    Event_version: "1",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2023-12-23T08:58:36",
    document_type: "TICKET",
    Event_number: "4",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 4,
    Flight_Number: 407,
    Airline_name: "HC",
    Departure_date: "2024-01-25T05:00:00",
    Board_Point: "DSS",
    Arrival_date: "2024-01-25T09:00:00",
    Off_Point: "JFK",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "JFK",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "EXRTUS1",
    Corporate: "72490460",
    Segment_Price: "115",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Issuance",
    event_date: "2023-09-13T03:13:50",
    document_type: "TICKET",
    Event_number: "0",
    Event_version: "0",
    Event_entity_status: "NOT CONFIRMED",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2023-12-22T23:04:11",
    document_type: "TICKET",
    Event_number: "2",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2023-12-23T09:00:46",
    document_type: "TICKET",
    Event_number: "5",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-23T08:58:35",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2024-01-24T22:49:41",
    document_type: "TICKET",
    Event_number: "6",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-23T08:58:35",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2023-12-23T08:58:36",
    document_type: "TICKET",
    Event_number: "4",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-23T08:58:35",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2023-12-22T23:06:35",
    document_type: "TICKET",
    Event_number: "3",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Association",
    event_date: "2023-12-22T08:11:49",
    document_type: "TICKET",
    Event_number: "1",
    Event_version: "1",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2024-01-25T09:12:36",
    document_type: "TICKET",
    Event_number: "9",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-23T08:58:35",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Confirm Issuance",
    event_date: "2023-09-14T00:39:46",
    document_type: "TICKET",
    Event_number: "0",
    Event_version: "1",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2024-01-25T09:10:21",
    document_type: "TICKET",
    Event_number: "8",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-23T08:58:35",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2024-01-24T22:51:53",
    document_type: "TICKET",
    Event_number: "7",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 1,
    Flight_Number: 408,
    Airline_name: "HC",
    Departure_date: "2023-12-22T01:30:00",
    Board_Point: "JFK",
    Arrival_date: "2023-12-22T14:50:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "JFK",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Seat_Request: "009D",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-23T08:58:35",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "618.5",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2024-01-25T09:10:21",
    document_type: "TICKET",
    Event_number: "8",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-22T23:04:11",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Issuance",
    event_date: "2023-09-13T03:13:50",
    document_type: "TICKET",
    Event_number: "0",
    Event_version: "0",
    Event_entity_status: "NOT CONFIRMED",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2023-12-23T09:00:46",
    document_type: "TICKET",
    Event_number: "5",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-22T23:04:11",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Association",
    event_date: "2023-12-22T08:11:49",
    document_type: "TICKET",
    Event_number: "1",
    Event_version: "1",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2023-12-23T08:58:36",
    document_type: "TICKET",
    Event_number: "4",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-22T23:04:11",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2023-12-22T23:06:35",
    document_type: "TICKET",
    Event_number: "3",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-22T23:04:11",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Confirm Issuance",
    event_date: "2023-09-14T00:39:46",
    document_type: "TICKET",
    Event_number: "0",
    Event_version: "1",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2024-01-24T22:49:41",
    document_type: "TICKET",
    Event_number: "6",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-22T23:04:11",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2023-12-22T23:04:11",
    document_type: "TICKET",
    Event_number: "2",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-22T23:04:11",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2024-01-24T22:51:53",
    document_type: "TICKET",
    Event_number: "7",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-22T23:04:11",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2024-01-25T09:12:36",
    document_type: "TICKET",
    Event_number: "9",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Pax_ID_Document_Number: "P-647127892",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 2,
    Flight_Number: 213,
    Airline_name: "HC",
    Departure_date: "2023-12-22T16:40:00",
    Board_Point: "DSS",
    Arrival_date: "2023-12-22T17:20:00",
    Off_Point: "BJL",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "DSS",
    Arrival_airport: "BJL",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2023-12-22T23:04:11",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "KXRTUS1",
    ssr_code: "ABAG",
    action_code: "MCF",
    service_type: "S",
    service_free_text: "2XBAG UPTO 23KG EACH JFK-DSS-BJL",
    chargeable_code: "0CC",
    Corporate: "72490460",
    Pax_ID_Document_Expired_Date: "20291125",
    Pax_ID_Document_Issuance_Country: "USA",
    Pax_ID_Document_Type: "P",
    Segment_Price: "49.46",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2024-01-24T22:51:53",
    document_type: "TICKET",
    Event_number: "7",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "N",
    Cabin_class: "N",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2024-01-24T22:49:40",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Issuance",
    event_date: "2023-09-13T03:13:50",
    document_type: "TICKET",
    Event_number: "0",
    Event_version: "0",
    Event_entity_status: "NOT CONFIRMED",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2023-12-22T23:04:11",
    document_type: "TICKET",
    Event_number: "2",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2023-12-22T23:06:35",
    document_type: "TICKET",
    Event_number: "3",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Association",
    event_date: "2023-12-22T08:11:49",
    document_type: "TICKET",
    Event_number: "1",
    Event_version: "1",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Confirm Issuance",
    event_date: "2023-09-14T00:39:46",
    document_type: "TICKET",
    Event_number: "0",
    Event_version: "1",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2024-01-24T22:49:41",
    document_type: "TICKET",
    Event_number: "6",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "N",
    Cabin_class: "N",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2024-01-24T22:49:40",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2024-01-25T09:10:21",
    document_type: "TICKET",
    Event_number: "8",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "N",
    Cabin_class: "N",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2024-01-24T22:49:40",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2023-12-23T09:00:46",
    document_type: "TICKET",
    Event_number: "5",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "Change of Status",
    event_date: "2023-12-23T08:58:36",
    document_type: "TICKET",
    Event_number: "4",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "Y",
    Cabin_class: "Y",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "O",
    document_status_updated_date: "null",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    },
    {
    Title: "MS",
    First_Name: "ISSATOU MS",
    Last_Name: "WAGGEH",
    event_type: "DCS Association",
    event_date: "2024-01-25T09:12:36",
    document_type: "TICKET",
    Event_number: "9",
    Event_version: "0",
    Event_entity_status: "VALID",
    Nationality: "USA",
    Date_Of_Birth: "1-6-2002",
    Flight_Segment: 3,
    Flight_Number: 214,
    Airline_name: "HC",
    Departure_date: "2024-01-24T22:15:00",
    Board_Point: "BJL",
    Arrival_date: "2024-01-24T23:05:00",
    Off_Point: "DSS",
    Marketing_Booking_Class: "N",
    Cabin_class: "N",
    Cabin_Category: "XXXXXXX",
    Departure_airport: "BJL",
    Arrival_airport: "DSS",
    Baggage_Allowance: "2",
    Document_Number: "4902410598875",
    Document_Status: "F",
    document_status_updated_date: "2024-01-24T22:49:40",
    conditions_of_the_ticket: "XXXX",
    Base_Tarifaire: "NXOWGM1",
    Corporate: "72490460",
    Segment_Price: "29",
    Currency: "USD",
    Type_Passager: "A",
    pnr_identification: "5B4OTS",
    uci: "3105227200074F97"
    }
    ];
    
    let segmentsCopy = [...segments];
    
    let passagers = segmentsCopy.filter((value, index, self) => {
      return self.findIndex(v => v.pnr_identification === value.pnr_identification) === index;
    }).map(item=>{return {pnr_identification: item.pnr_identification, First_Name: item.First_Name, Last_Name: item.Last_Name}})
    
    // console.log(passagers);
    
    let selectedPassagerPNR = '5B4OTS';
    
    let uniqueSegmentForSelectedPassagers = segmentsCopy.filter(item=>item.pnr_identification===selectedPassagerPNR)
    .filter((value, index, self)=>{
      return self.findIndex(v => v.Flight_Segment === value.Flight_Segment) === index;
    }).sort((item1,item2)=>{
    return item1.Flight_Segment-item2.Flight_Segment;
    })
    
    //console.log(uniqueSegmentForSelectedPassagers);
    
    let selectedSegmentNumber = 1;
    
    let historics = segmentsCopy.filter(item=>item.pnr_identification===selectedPassagerPNR)
    .filter(item=>item.Flight_Segment===selectedSegmentNumber);
    
    
    
    
    
    